- hosts: all
  tasks:
    - name: Test password
      debug:
        var: "u7805-password"
    - name: Update and upgrade yum packages
      become: true
      yum:
        name: "*"
        state: latest

    - name: Add user 'u7805' and grant to 'admin' group
      user:
        name: u7805
        comment: Josh Perkins
        uid: 1200
        group: wheel

    - name: Set authorized keys taken from github
      authorized_key:
        user: u7805
        state: present
        key: https://github.com/riorescue/WrkAnsWindowsTesting/raw/master/u7805auth.pub
