- hosts: all
  vars_files:
    - pwvault.yml
  tasks:
    - name: Change the hostname to our standard
      hostname:
        name="{{ hostname }}"
      when:
        ansible_fqdn != ansible_ssh_host

    - name: restart machine
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: True
      when:
        reboot is defined

    - name: Waiting for server to come back up
      local_action: wait_for host="{{ inventory_hostname }}" port=22 state=started

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        line="{{ ansible_default_ipv4.address }} {{ hostname }} {{ ansible_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != hostname

    - name: Validate ansible_fqdn == hostname
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == hostname

    - name: Test password
      debug:
        var: password
    - name: Update and upgrade yum packages
      become: true
      yum:
        name: "*"
        state: latest

    - name: Add user 'u7805' and grant to 'admin' group
      user:
        name: u7805
        comment: Josh Perkins
        password: "{{ password }}"
        uid: 1200
        group: wheel

    - name: Set authorized keys taken from github
      authorized_key:
        user: u7805
        state: present
        key: https://github.com/riorescue/WrkAnsWindowsTesting/raw/master/u7805auth.pub

    - name: Install required docker packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: yes

    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
      when:
        - docker_compose_check.msg is defined
        - docker_compose_check.msg.find('No such file or directory') != -1
