---
- hosts: TestingSvr2016
  gather_facts: true
  tasks:
    
    - name: Ensure temporary directory exists at root of C:\
      win_file:
        path: C:\Temp
        state: directory
      when: ansible_facts['ansible_os_name'] == "Microsoft Windows Server 2019 Datacenter"

    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        log_path: C:\temp\ansible_wu.txt
        reboot: yes
        reboot_timeout: 400